FROM ghcr.io/cross-rs/aarch64-unknown-linux-gnu:0.2.5

RUN dpkg --add-architecture arm64 && \
    apt-get update && \
    apt-get install -y --no-install-recommends \
    libspeechd-dev:arm64 \
    && ln -sf /usr/include/aarch64-linux-gnu/speech-dispatcher /usr/include/speech-dispatcher \
    && rm -rf /var/lib/apt/lists/*
