[build.env]
passthrough = ["CARGO_TERM_COLOR"]

[target.aarch64-unknown-linux-gnu]
image = "ghcr.io/cross-rs/aarch64-unknown-linux-gnu:0.2.5"
pre-build = [
  "dpkg --add-architecture arm64",
  "apt-get update || true",
  "apt-get install -y --no-install-recommends libspeechd-dev:arm64",
]
