FROM ghcr.io/cross-rs/aarch64-unknown-linux-gnu:main

RUN apt-get update && \
    apt-get install -y libspeechd-dev libclang-dev && \
    cp -r /usr/include/speech-dispatcher /usr/aarch64-linux-gnu/include/speech-dispatcher && \
    cp /usr/include/libspeechd_version.h /usr/aarch64-linux-gnu/include/ || true

ENV BINDGEN_EXTRA_CLANG_ARGS="-isystem /usr/include"
